name: Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8", "3.9", "3.10"]
        install: [install, develop]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - name: Disable etelemetry
      run:  echo "NO_ET=TRUE" >> $GITHUB_ENV

    - name: Install System Packages
      run: sudo apt install libopenjp2-7

    - name: Install Dcm2niix
      run: |
        curl -fLO https://github.com/rordenlab/dcm2niix/releases/latest/download/dcm2niix_lnx.zip
        unzip dcm2niix_lnx.zip
        mv dcm2niix /usr/local/bin

    - name: Install Minconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: true
        activate-environment: ""

    - name: Install MRtrix via Conda
      run: |
        conda install -c mrtrix3 mrtrix3
        mrconvert --version

    - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Update build tools
      run: python -m pip install --upgrade pip setuptools wheel

    - name: Install Pydra tests dependencies (develop or setup.py install)
      if: matrix.install == 'develop' || matrix.install == 'install'
      run: pip install ".[test]"

    - name: Install dependencies (setup.py install)
      if: matrix.install == 'install'
      run: python setup.py install

    - name: Pytest
      run: pytest -vvs --cov arcana  --cov-config .coveragerc --cov-report xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
